print(5+9)
print(9*6)
print("your name")
print("Hello World!")
name = input('What it your name?')
print(f"Hello {name}")
number = input("guess a number from one to nine ")
import random
number = random.randrange(10)
print(number )
number = random.randrange(9)
print(number )